name: Rust Lint, Format & Test

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        run: rustup update stable

      - name: Run Clippy
        run: cargo clippy -- -D warnings

      - name: Check Formatting
        run: cargo fmt -- --check

      - name: Run Tests
        run: cargo test --all
