name: Rust CI

on: [push, pull_request]

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # TODO:
      # integration tests demand ollama and qdrant
      # update usage to nextest
      # - name: Install Rust
      #   run: rustup update stable

      - name: Install tarpaulin
        run: cargo install cargo-tarpaulin

      - name: Run Unit Test Coverage
        run: cargo tarpaulin --out Xml --lib

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: PerminovEugene/messy-folder-reorganizer-ai
